apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/thomvandevin/homelab
    path: apps
    targetRevision: main
