grafana:
  ingress:
    enabled: true
    hosts:
      - "grafana.home"
  persistence:
    enabled: true
    type: sts
    storageClassName: ""
    accessModes:
      - ReadWriteOnce
    size: 5Gi

prometheus:
  ingress:
    enabled: true
    hosts:
      - "prometheus.home"
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
