apiVersion: v1
kind: Namespace
metadata:
  name: limitless-tournament-decks
  labels:
    name: limitless-tournament-decks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: limitless-tournament-decks
  namespace: limitless-tournament-decks
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: limitless-tournament-decks
  template:
    metadata:
      labels:
        app: limitless-tournament-decks
    spec:
      imagePullSecrets:
        - name: gcr-limitless-tournament-decks-secret
      containers:
        - name: limitless-tournament-decks
          image: gcr.io/limitless-tournament-decks/limitless-tournament-decks
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_HOST
              value: postgresql.db-system.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: limitless_tournaments_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DATABASE_URL
              value: postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql.db-system.svc.cluster.local:5432/limitless_tournaments_db
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: limitless-tournament-decks-svc
  namespace: limitless-tournament-decks
spec:
  type: ClusterIP
  selector:
    app: limitless-tournament-decks
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: limitless-preload-onepiece
  namespace: limitless-tournament-decks
spec:
  schedule: "0 */3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl:latest@sha256:935d9100e9ba842cdb060de42472c7ca90cfe9a7c96e4dacb55e79e560b3ff40
              args:
                - curl
                - -X
                - GET
                - http://limitless-tournament-decks-svc.limitless-tournament-decks.svc.cluster.local/preload?game=OP&maxTournaments=20&preloadStandings=true&preloadDecklists=true&maxDecksPerTournament=-1
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: limitless-preload-pokemon
  namespace: limitless-tournament-decks
spec:
  schedule: "0 */3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl:latest@sha256:935d9100e9ba842cdb060de42472c7ca90cfe9a7c96e4dacb55e79e560b3ff40
              args:
                - curl
                - -X
                - GET
                - http://limitless-tournament-decks-svc.limitless-tournament-decks.svc.cluster.local/preload?game=PTCG&maxTournaments=20&preloadStandings=true&preloadDecklists=true&maxDecksPerTournament=-1
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: limitless-cleanup
  namespace: limitless-tournament-decks
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl:latest@sha256:935d9100e9ba842cdb060de42472c7ca90cfe9a7c96e4dacb55e79e560b3ff40
              args:
                - curl
                - -X
                - GET
                - http://limitless-tournament-decks-svc.limitless-tournament-decks.svc.cluster.local/cleanup
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
          restartPolicy: OnFailure
