apiVersion: v1
kind: Namespace
metadata:
  name: scraper
  labels:
    name: scraper
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: db-secret
  namespace: scraper
data:
  password: {{ .Values.db.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: scraper-secret
  namespace: scraper
data:
  user: {{ .Values.pushover.scraper.user | b64enc | quote }}
  token: {{ .Values.pushover.scraper.token | b64enc | quote }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: gcr-scraper-secret
  namespace: scraper
data:
  .dockerconfigjson: {{ .Values.gcr.scraper | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  namespace: scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      imagePullSecrets:
        - name: gcr-scraper-secret
      containers:
        - name: scraper
          image: gcr.io/cavempt-scraper/cavempt-scraper
          ports:
            - containerPort: 8080
            - containerPort: 8443
          env:
            - name: POSTGRES_HOST
              value: postgresql.db-system.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: scraper_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DATABASE_URL
              value: postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql.db-system.svc.cluster.local:5432/scraper_db
            - name: PUSHOVER_USER
              valueFrom:
                secretKeyRef:
                  name: scraper-secret
                  key: user
            - name: PUSHOVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: scraper-secret
                  key: token
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: scraper-svc
  namespace: scraper
spec:
  type: ClusterIP
  selector:
    app: scraper
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper-job-short
  namespace: scraper
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl:latest@sha256:d94d07ba9e7d6de898b6d96c1a072f6f8266c687af78a74f380087a0addf5d17
              args:
                - curl
                - -X
                - GET
                - http://scraper-svc.scraper.svc.cluster.local/update?sources=pokebeach&rottencloset&kaiofcards
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper-job-long
  namespace: scraper
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl:latest@sha256:d94d07ba9e7d6de898b6d96c1a072f6f8266c687af78a74f380087a0addf5d17
              args:
                - curl
                - -X
                - GET
                - http://scraper-svc.scraper.svc.cluster.local/update?sources=cavempt
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
          restartPolicy: OnFailure
