apiVersion: v1
kind: Namespace
metadata:
  name: cavempt-scraper
  labels:
    name: cavempt-scraper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cavempt-scraper
  namespace: cavempt-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cavempt-scraper
  template:
    metadata:
      labels:
        app: cavempt-scraper
    spec:
      imagePullSecrets:
        - name: cavempt-scraper-gcr-key
      containers:
        - name: cavempt-scraper
          image: gcr.io/cavempt-scraper/cavempt-scraper
          ports:
            - containerPort: 8080
            - containerPort: 8443
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: cavempt-scraper-gcr-key
  namespace: cavempt-scraper
data:
  .dockerconfigjson: {{ .Values.gcr.cavempt_scraper | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: cavempt-scraper-svc
  namespace: cavempt-scraper
spec:
  type: ClusterIP
  selector:
    app: cavempt-scraper
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cavempt-scraper-job
  namespace: cavempt-scraper
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:latest
            args:
              - curl
              - -X
              - GET
              - http://cavempt-scraper-svc.cavempt-scraper.svc.cluster.local/update-all
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 100m
                memory: 128Mi
          restartPolicy: OnFailure