apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://cloudflare.github.io/helm-charts
    chart: cloudflare-tunnel
    targetRevision: 0.3.2
    helm:
      valuesObject:
        cloudflare:
          tunnelName: "homelab"
          tunnelId: "8ea8da25-8b7a-4b64-b3e5-b3624680679c"
          secretName: "tunnel-credentials"
          ingress:
            - hostname: "homelab.thomvandev.in"
              service: http://echo-svc.echo.svc.cluster.local
            - hostname: "cavempt.thomvandev.in"
              service: http://cavempt-scraper-svc.cavempt-scraper.svc.cluster.local/cavempt
            - hostname: "pokebeach.thomvandev.in"
              service: http://cavempt-scraper-svc.cavempt-scraper.svc.cluster.local/pokebeach/rss
  destination:
    namespace: cloudflare-tunnel
    server: https://kubernetes.default.svc
