apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://cloudflare.github.io/helm-charts
    chart: cloudflare-tunnel
    targetRevision: 0.3.2
    helm:
      valuesObject:
        cloudflare:
          secretName: "tunnel-credentials"
          ingress:
            - hostname: "murfzw.online"
              service: http://echo-svc
            - hostname: "*.murfzw.online"
              service: http://echo-svc
  destination:
    namespace: cloudflare-tunnel
    server: https://kubernetes.default.svc
