apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: tunnel-credentials
  namespace: cloudflare-tunnel
data:
  credentials.json: {{ .Values.cloudflare.secret | b64enc | quote }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://cloudflare.github.io/helm-charts
    chart: cloudflare-tunnel
    targetRevision: 0.3.2
    helm:
      valuesObject:
        cloudflare:
          tunnelName: homelab
          tunnelId: 8ea8da25-8b7a-4b64-b3e5-b3624680679c
          secretName: tunnel-credentials
          ingress:
            # Homelab
            - hostname: homelab.thomvandev.in
              service: http://echo-svc.echo.svc.cluster.local
            # Home Assistant
            - hostname: homeassistant.thomvandev.in
              service: http://home-assistant.home-assistant.svc.cluster.local:8080
            # Scraper
            - hostname: scraper.thomvandev.in
              service: http://scraper-svc.scraper.svc.cluster.local
            - hostname: cavempt.thomvandev.in
              service: http://nginx-reverse-proxy.default.svc.cluster.local
              originRequest:
                httpHostHeader: cavempt.thomvandev.in
            - hostname: rottencloset.thomvandev.in
              service: http://nginx-reverse-proxy.default.svc.cluster.local
              originRequest:
                httpHostHeader: rottencloset.thomvandev.in
            - hostname: pokebeach.thomvandev.in
              service: http://nginx-reverse-proxy.default.svc.cluster.local
              originRequest:
                httpHostHeader: pokebeach.thomvandev.in
            # Decklist
            - hostname: decklists.thomvandev.in
              service: http://limitless-tournament-decks-svc.limitless-tournament-decks.svc.cluster.local:80
            # Swiss Rounds
            - hostname: swissrounds.thomvandev.in
              service: http://swiss-rounds-svc.swiss-rounds.svc.cluster.local
            - hostname: swissrounds.app
              service: http://swiss-rounds-svc.swiss-rounds.svc.cluster.local
            - hostname: "*.swissrounds.app"
              service: http://swiss-rounds-svc.swiss-rounds.svc.cluster.local
            # End of year
            - hostname: end-of-year.thomvandev.in
              service: http://end-of-year-svc.end-of-year.svc.cluster.local:80
            # Sharry
            - hostname: sharry.thomvandev.in
              service: http://sharry.sharry.svc.cluster.local:9090
  destination:
    namespace: cloudflare-tunnel
    server: https://kubernetes.default.svc
