apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://cloudflare.github.io/helm-charts
    chart: cloudflare-tunnel
    targetRevision: 0.3.2
    helm:
      valuesObject:
        cloudflare:
          tunnelName: "homelab"
          tunnelId: "e619bd2a-64b8-48b0-a9d0-cda9dfa7d2b0"
          secretName: "tunnel-credentials"
          ingress:
            - hostname: "murfzw.online"
              service: http://echo-svc.echo.svc.cluster.local
            - hostname: "test.murfzw.online"
              service: hello_world
            - hostname: "router.murfzw.online"
              service: http://192.168.1.1
            - hostname: "factorio.murfzw.online"
              service: udp://factorio-factorio-server-charts.factorio.svc.cluster.local:31497
            - hostname: "*.murfzw.online"
              service: http://echo-svc.echo.svc.cluster.local
  destination:
    namespace: cloudflare-tunnel
    server: https://kubernetes.default.svc
