apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: sharry-secret
  namespace: sharry
data:
  password: {{ .Values.sharry.password | b64enc | quote }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sharry
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://geek-cookbook.github.io/charts/
    chart: sharry
    targetRevision: 5.4.2
    helm:
      valuesObject:
        service:
          main:
            ports:
              http:
                port: 9090
        ingress:
          main:
            enabled: false
        config: |
          sharry.restserver {
            base-url = "https://sharry.thomvandev.in"
            bind {
              address = "0.0.0.0"
              port = 9090
            }
            backend {
              signup {
                mode = "closed"
              }
              share {
                max-size = "10G"
              }
              auth {
                fixed {
                  enabled = true
                  user = "admin"
                  password = "{{ .Values.sharry.password }}"
                  order = 10
                }
              }
              jdbc {
                url = "jdbc:h2:///var/sharry/db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"
                user = "sa"
                password = ""
              }
            }
          }
        persistence:
          config:
            enabled: true
            mountPath: /var/sharry
            size: 10Gi
  destination:
    namespace: sharry
    server: https://kubernetes.default.svc
