apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: github-secret
  namespace: actions-runner-controller
data:
  github_token: {{ .Values.gh.token | b64enc | quote }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    chart: actions-runner-controller
    targetRevision: 0.23.7
    helm:
      valuesObject:
        authSecret:
          create: false
          name: github-secret
          key: github_token
  destination:
    namespace: actions-runner-controller
    server: https://kubernetes.default.svc
