apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.3.6
    helm:
      valuesObject:
        global:
          domain: argocd.home

        configs:
          params:
            server.insecure: true

        repoServer:
          metrics: &metrics
            enabled: true
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: prometheus

        server:
          ingress:
            enabled: true
            ingressClassName: tailscale
            tls: true
            extraTls:
              - hosts:
                  - argocd
          metrics: *metrics
        controller:
          metrics: *metrics
        applicationSet:
          metrics: *metrics
        notifications:
          metrics: *metrics

  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
