apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cavempt-scraper
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://gitlab.com/thomvandevin/cavempt-scraper
    targetRevision: HEAD
    path: helm

    helm:
      valuesObject:
        grafana:
          ingress:
            enabled: true
            ingressClassName: tailscale
            tls:
              - hosts:
                  - "grafana"

  destination:
    server: https://kubernetes.default.svc
    namespace: cavempt-scraper

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
