apiVersion: v1
kind: Namespace
metadata:
  name: limitless-tournament-decks
  labels:
    name: limitless-tournament-decks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: limitless-tournament-decks
  namespace: limitless-tournament-decks
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: limitless-tournament-decks
  template:
    metadata:
      labels:
        app: limitless-tournament-decks
    spec:
      imagePullSecrets:
        - name: gcr-limitless-tournament-decks-secret
      containers:
        - name: limitless-tournament-decks
          image: gcr.io/limitless-tournament-decks/limitless-tournament-decks
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: limitless-tournament-decks-svc
  namespace: limitless-tournament-decks
spec:
  type: ClusterIP
  selector:
    app: limitless-tournament-decks
  ports:
    - name: http
      port: 80
      targetPort: 3000