apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  default.conf: |
    server {
        listen 80;
        server_name cavempt.thomvandev.in;

        location / {
            proxy_pass http://scraper-svc.scraper.svc.cluster.local/cavempt;
        }
    }

    server {
        listen 80;
        server_name rottencloset.thomvandev.in;

        location / {
            proxy_pass http://scraper-svc.scraper.svc.cluster.local/rottencloset;
        }
    }

    server {
        listen 80;
        server_name pokebeach.thomvandev.in;

        location / {
            proxy_pass http://scraper-svc.scraper.svc.cluster.local/pokebeach/rss;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-reverse-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-reverse-proxy
  template:
    metadata:
      labels:
        app: nginx-reverse-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:1.29@sha256:84ec966e61a8c7846f509da7eb081c55c1d56817448728924a87ab32f12a72fb
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-reverse-proxy
  namespace: default
spec:
  selector:
    app: nginx-reverse-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80