apiVersion: v1
kind: Namespace
metadata:
  name: scraper
  labels:
    name: scraper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  namespace: scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      imagePullSecrets:
        - name: scraper-gcr-key
      containers:
        - name: scraper
          image: gcr.io/cavempt-scraper/cavempt-scraper
          ports:
            - containerPort: 8080
            - containerPort: 8443
          env:
            - name: POSTGRES_HOST
              value: postgresql.db-system.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: scraper_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password | quote }}
            - name: PUSHOVER_USER
              value: {{ .Values.pushover.scraper.user | quote }}
            - name: PUSHOVER_TOKEN
              value: {{ .Values.pushover.scraper.token | quote }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: scraper-gcr-key
  namespace: scraper
data:
  .dockerconfigjson: {{ .Values.gcr.scraper | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: scraper-svc
  namespace: scraper
spec:
  type: ClusterIP
  selector:
    app: scraper
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper-job
  namespace: scraper
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl:latest@sha256:4026b29997dc7c823b51c164b71e2b51e0fd95cce4601f78202c513d97da2922
              args:
                - curl
                - -X
                - GET
                - http://scraper-svc.scraper.svc.cluster.local/update-all
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
          restartPolicy: OnFailure
