---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-secret
  namespace: tailscale
spec:
  encryptedData:
    clientId: AgAhwLY6MZkJjJ9b4H2KRKE7OUFNzC7s3ZqdgmdRIkf1jxTLf0OiuJQG6DEaHVRpqAnX+rnY/7WgzqDxiWubgHumwyBkwgyQflXFiHsLjvVbN10d6KWmTt6hH/dKWVomobDdD/eRmaL7EU9Wl9qm4FJOTpxBzGuiZSH+/o1hKyZoR/bjPK7xnUndWceYpVkmFCDsjwMgHdIaorZcy1kYrCTaNakbeEjFvjPTQzeLwCq2g5OOMxBXJt7CyV+9kjZVOs+b34922YjMBjNexKoiSZyrBdTWhqYD6iSMZeIf1Y5D64YkHZa+TNcCJkPYGoVUo83Y1joebdiatMboCN9NAN08wcRgFcwOQTzfy0KwxKhMoMLNNcxZEcCCB7O1NmiKxg3+EtxEFNuSlBN3WPQ8cq+09Cn2sfqxBeJ7g4CaT6UpQVgVe3TfK6d2WyoQR3/nPWd1uihlmt/1hmmLX33/rysK03Hsb9NUMGHRT0gPyc+mVJ65KHFx6uz1TlfNhoTElZYlKEoBl+jgppi5Hj5y0oVfKfosECn80/AaQZ2oexTYvv5IyprUjj/FqFQymukSqNuq01RBEdo7sLoOv1FdfGZ8YPfnzhAy1hbc2hilfZfEIlaO6yJwiGGPT3GdZQUc7uK8Lj9ivw0Jr7g8qRZBqgf9+eabowZejtTDakw+0OF7wCKmKxeRBq7QEYrQOQ2oXm/rrSzRY23ZMRRjtAOQlXHFHQ==
    clientSecret: AgAECPPXQHnZbKTibLYeDzQ67SlIBvGnL3EeoXUMNN9Y2CHkFAkoOm2SlptgpKk5CAaCwCorfBgbkEnVLj2yJrHV1BsHx/yclKR08vyPTKeG4Hg6hzDAhultCniiDTanXzBGLpi/1rzCeIZrqAji4OAiW08NQvcOJskqyELZbprgaVlDHR4ORRtjMy9RyXhPU0jPVXHrS1JEy7tm5sMhduJFlLRlpDOhFeeUGgms1tRBOLe9G6kktEorQYZ8Au8ouPLOjrrcjPplJiSfpQfHzqFXgBVfuASSLobOr15gsBeVFYZ0Smn0Hit7IryFxwspSyZZhyCPZjB/d/YUgdHS9XoXturoI98MBFF04qaMMoHDTiZqL030+hHXu6YIAgT7i5OGGqucEgusMyLHoUKnRqVRo/G/zLUiRQtYxZuisAQao3ibn1W2Pdmk6dJhvhvlexi0I9Qujgu76uJbzfNjxQyKvsaJX7D/9N07PHrDTG0Y2m0Icu9IBEYKlj+deaBGFTmpxCxsISh4C6A7UpYueVhBsPxGC7KmVrKNDO3xWnEksVXYC4v0Suue79Sz6CkIllm4TcxigpgBrveXmHDVZ3/1FzsCd2eOZSUQCtCZasT+CAsANJN/dDcp7FIWUTCh02eHGoMd3mxK6YJgrNF9VSm1PQEgZdE9O8adVy+T1m7lOt3UU3aXmhxkZaIurZ+pJ/S9Lap8+1oZjcvjIixkI7bT2DdE2tkc669KhgxPoY9uLO+DOE7NIU0E8fBivAgmG2ww7u+KosDqzHPUwnDLYLA=
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-secret
      namespace: tailscale
