---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: default
spec:
  encryptedData:
    secret: AgBA0LTNm/uvDYZ9boh3qkdjIUHLWTqgBZte4JdPJkLWOlNRDBEFs6NcSF99Q9qCHx8F6NVsW4o0G1GnU7/JYuKqz1j/LqRPrcYL4Xu41KPSVeCIA05xxOQ7B3A9TfNjrd0GglG6YxOlUuoU7OF3BKupudjGN0aPx3CD+RAPtq05d8yFqyYbgOp1f3yUydCdU897mjmqV08Unksq0Xm5fUou+UvV7AWHIwaBzHRFOCvrf2SomkRzU4lK87uIcLkeY4813F/Yd/4WWS3sZNDwkJimn92EKYvTvlM9UAn5Exoi366iTF0QzqUndBLz3glguCreT7dBqS9CpQ/mMA7IwQ3BN1Zi2HP0VPC4uE7yE8jL6Aw31Y8zp+a8At+KdIE+zzq6BrDkvCN3lVDSlEORnWe8YsMJSrVEB+mJuE1wKY8dDNzybBqLHB7b9r32/8MflKZjdeAH3++Y3D9oYZ7Go0xuga5cRCYiu59VSKVN0edjBArOARU4d0wzLuZ2ohUAl7ORo96ysKi3mUt91MjDquaTdNDb2cZaAOhWWxq5goiP/bIw02kV9zjmgcpVro8Esj2TgUzgI+ueg7YpLJoVTFu8uEeL9WMspH6HReztdpk74k8b8LOEABJQyZwrqX8cNucicJ+g886S3uAqmQOMsxapRDFoagziGKJQg6JB9XSAauj/WHzzOQelBaG4w3EFJvw9urbJVIzv6s1qmDs1m2DHArUHPZF5g8oH6E8pezlzXzw5YC60mojaRaSUZzH7NKXa4OWXUrqY8FBwJgsFlZQN7F0aoFSv7o41S9IU0PxMWCTS3PwZbnZjfIT2EmqVpzE4QHNR/2A5zECOqWm8eHAbAhiOz8gFCtWsthNaE6zBS/r8JRfxD+ak5TWRmBby+kyKWBRLCTrwYJ6z6OAP5inAnXSU1W/kS+OiWVlvAxPt
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: default
