---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: limitless-tournament-decks
spec:
  encryptedData:
    password: AgBsNS8dqoJiHe32I2UcJs2S886gYBgS1WJW7DviRlv7BCSZU1IfMGXM8YYcG03PmoVTiB/LW2j3zVYbKcQFqWx8h5D+oouDiFzUVYiuAd/OosjtpRsqzA8bTUPsF+RqbS1sed+AeKdb0goiueKDTxM3nzA1GEOMWc0lsTBXUDmvXjUUbZHgMHUNt544zzMxyjar4Mar9VFs+oDs2Co4cBzHI3xxcctk+kGaPsEyGAyddkjbci9jmABLJWa8TDCM0JsWHcl8XWDwZGt4H9w/7v9uHCzpug9SNc5lHbsr3EB9r+l6bnQvuJIJTwQpVmZzah+oMb3IBcR9LGS3L0xWNSLzL9AF8LirODgzW1ZWRr6dnp+DJexuBRRmjVaSI2e8p3ebVLzYKzpWnNnNflWnREcivEwwCeGQCg9qjzVQ+tvpMPSVJubjt7iN3wq242Or+hA9Nr0bQMKEdxSkvYPFpzoJvRL6fdDCGkh8A0r2+BClGNoXZX3ajocHWwkx6K6YeS6BdraD0C0i4l80IFI5UW6BQaId87LazQUP7W4+/tdOhc4tku3ettuC3+PXNwD4beFdKBTBBG1MfHPTNCXf1IxwBfluhT5rwRMAC7KVLqOo3/6x8cQIg068eI01wI5DtUATWeMAjRT7xyf9mc9ql34nfnxsaIsutv9ecA30r26Dw63kQsot2P2UspQg1Q/uQ+3zscrEb1xoOXS/vog=
  template:
    metadata:
      name: db-secret
      namespace: limitless-tournament-decks
