---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    credentials.json: AgAhrWtjhyinpX9mMCVvNG2E3PGpbdLQqr+qeTHFSEBQLoUIKnjXwHKnSF5jzVJEmk0lwGjIMNhvQNeiRZfgDimp+lTf63w3aODaNLoGvMs6rDBj/iivN2ag3xTAjvktIR8+XQREfV88pKmO10a58yxNl6UVv2qKjMiKnK5sLqrGLjxpxAtDjBNB0+FmDVKh0OhbLV+gPhuUCGJhFAHeusu7efn+dlBHbdI9+aFaQ9O0YG16qKZTYJg4NetxkitdwMRe6jZIAoJdEfATGxqx7pjErjKGT3/nyNR27cuOrtYw3ryb0FD4sxABRLMOCZfDhUXYU86hNepzFY6Y4scj8Bv5I163zCRaWahkm5IzWhLOd7xSnANyPYL3YFf8aCfYkesBTW7YJtnltxB6uAFakeEG8b31OaIcRGizNDeILF+ks0jPhnMDpVPot0gVocSaEFz2M6bNh4aha0VEwGwGKIiQKvXI3SJUkx9QP2HrUQ+NBh4KVqQY5zJwTKymwf10xxVEwnIRyl7bjxDb5CjIQrWvhSvgio9fr6i1wAHvZRkV3vRNZbyG+iCp3dh8yrOQICnXtRHDKmfV1TAD19qa90yIYrPqpH6TEE84hadhLEVaMbQw3QI3cMs9V8FweQpgiq2PAYRaw1jJvdwPLin11J22fpw279yJc9hOCDSdxvKksoD5mPWUbncGxVXgc1ItHsKquT9oGRTGpROCcire8F3fRaTOEyzWwmMTM8LWRrGfW57UMaO3sUXUKyvtRp6YlXPIiLO+u32o4FWHTi71CIm3BUALVDxAM4QV2BNawkPazsY6VGxMONhjiNgfcOp3D+h3H6hjTHeVpvXqS9hQSLzj7/fhrUFCpm6Ps8aivDEKKYhDWUoogVUSVt5D5gmcAc229FHIvxzjgnI5BasyVWk1c2HEtj5Dcmlx5kcOOtKC
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare-tunnel
