---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-secret
  namespace: actions-runner-controller
spec:
  encryptedData:
    github_token: AgBztYc13R0qd7b2BdZMXRXFNPNzYR52mRKlpZTD41olOo5cPIUlEYwa+YJKAqi/CIYa7RNwnxT3MJSTEmLrbQA37IkI0Gxk7WE5nmG0mubBjfKp7ap27Q4eb7sArlh46IwmFMlX3aWWRLojHnR9/9EY8RBs+Ma0Z0Uii++PiBBaOMPYAKGKjXSh4YDW1pSZWWFG8I73/3U+zTrMNaYY0efy5td/UEYSiO4x7dSLaAz7QbAwuA2KRwmP+VMiLZvFWPStkPqdCHwLCD/8V7l7p4k1pQdhwese/usH5Z1+MOMpvFvsFEhkrKad8bhRNtWt87cSVPvKLiRAKwzlfuuJU9rvWNJwcnlv4pmwCB3sKgP5bbJXEHeY28SUy7sQm1cMQHWS42CoNL1boQyvFs7H/cUOiGBnLq+fJrTfsDYc+20cteigfrjF2BkiKtT9KWfu09XV3BdS0oorGmul5HPw2uMRjw7l3rCmxWQXZSUT+RdGMw4s2NTO52f8Ngarg2XHnh0jVvWxnw4p47eLi5hnvXY4wdj3IAtdQqjgbVEMbNlU2xqFl/FyWRiEQsrXgLpZZX52Liv/GPNqjBiRhyVDN1dWJjP5iVlIW5iDkbjGKm1BE32At3kVQSBwX++V+ugCutS0R2tnpohrD/fxU4XYqn/WUIpzvkIjkIr430STThYSj2DXbhIRqS21w6bIpo7qhHXg1Bnd3EsjcUvQx6P+02EjvArgBRRrZeazhdDRAdBPHhx4yzOCrLk17V8Kt2P34L0Gh91q+2mHbkC6Qi5So3rwiDo4+gPZFJMVzB3t2MuxE326M25lmWtOKzvxAks=
  template:
    metadata:
      name: github-secret
      namespace: actions-runner-controller
