---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sharry-secret
  namespace: default
spec:
  encryptedData:
    db_password: AgBbJcrQZgNy3/raEFqACRmg9pmYdDyB3SzwsvzK8dV2w0Jw1n7IEYf6Gc1g1VRXfWZYhpP5F/Dbr6YXtxQa6aTOvKAzC4zQzdFoij0YppZKkzpNdoLFB2RQXYGqSfOV6jg9Q38AFgkmFAdpDeEzOF0YCKJsuaLy310PcsRYtct3jq8cup4NCpBB+/MlLrWagRuZBhjgonCCRUerzJi0WMxV4rIIQWHdvosJ1oa/XGDuuucvX0Bjw4dKrBh+qrKo7Lm5MZ54+Ic9wsnOr9H0NfWsDnPzSuWbjGp+Ja1jPYGFaAY2D0ST/MpUnRoHcfew97p78GZNbt0Lk0CMxJd4DGgDNuX3kLCIy2ZqyqHwnXVuhDv+4J94GLjw/hCaqUcKiBJ4RjnlHO4Eax8xiwsjCy7twulvdvW8CJkySixeFQonv8400Qk4bM1qa8C4R9wOg21LeL/FUbYfhNWJker8DFCqA7bjEDYy6vQ/rDb0quj0cx7nsZ3q9oEPS7RGGKIGnw2sGvwjYBB/slZ7iq3E4rjsvLxxAzgjmkMaqY/aKWAaIAAGqt0RauKXbvuQsGNUmcuORMozgbGZraornm22SUR7VDmIygWX/BiAsrkDQoqmiS+bhXs92AP8FWOvqExILq/Gm+QF328C7Gu+RBAtHQMlp07oNddb4JVnwSNc3nfF2WmRv45dNUGRBbSJPJdcU2mIuJBLaHOYGAn7Fzo=
    password: AgBBtqS0VrEcIAuqc90jyAGLWpvxvS3zLQ8Ta6RTtJ9rtmt18JPUJRluIK+Fm2mJwlGtZyOaZWnOauoi7ZDY0VvhrO9cV8X5TA2nDfic4izaBEjN0TSNU3/0xAQbylUGsSiWEqnKp/uE89Ywwlozz3nkrHavGim1EgBQn5mn80//+VJS0DcO7D8TX9W9ALUjVIlZk1lgy5m/Qd1r8BY208OWdTPp6X4hC0I/NvCgmU7ubZt/bznEK7as3lrwf1JHtifffNvljI3WBZnUszRirJ1DEIFlsBeJsmdpqmO5OvBuCjhrciABrT/7INUc5HEqJRczq3qxhnyjuXLtLLWrfyW/3xS7mGsC4QB/PVfPbd4IYrMYkkAh76dcVr9ryjb1JC40nfxEMhudRbfNp8mEvj0yIpPrK7nqvGvufIXQUAKGEy2d4AbA4d6EVrtIrXCLozZ+0y0eIpE49IN/6OKefwlZcYAWOu5CoWB+5fObQWjwEakiDxwRtCodWiNxxCRePa2Ygh4oTLdCqLWrpK/t7TDZYieJF8ofvtliv+miwxnFPljuI7OTj2vqfN2jTu6luAf/wWEdlFIsYIQ6LvJEwYW1aWpt5E1f0oj8nMSeNBfMj65Xb7ZbA9Sd+Jeitb/71SgAqknTP691Q3AjdKqMZTm/9qUSIe6NcoPVo5lK6bhn+r0oIK2RdPyOsp8TrNWl4WFXjxZ/xEY3L0bJ8Xg=
  template:
    metadata:
      creationTimestamp: null
      name: sharry-secret
      namespace: default
