---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: limitless-tournament-decks
spec:
  encryptedData:
    password: AgBb9cEmFPSbIFSb8OMUSrVAIuxMUbpjhENGwLw/eGrJhEzjK1CazZcPg6Fz8J+c8lJsdJh2j7ng7FrEBNcXKRK7zy9nfYUQ+M707A+7j6jYFc7fgruUHnE09Gk1YuNbSUMWY1PaCI4rXzfOOpkH/AAQv0jV7vRvg+eP0NI6GguYkS659dZCjGAcB3ea3l1jDXs29mF9IWZIeCFrvc2uAokxqn5e3IPhW75+sqKJrVOalHhNjE9bCLL6TzYbzqzy59k3dd/ARiKHXmSNGS01BbmlSMWmwBrYErTayc7balW/ajiyXs4b6bvr82rzk0cgWQJMXjlq1kF/NQ9ovAICQrGhNyoCjhZwHSBPcLqs8OT4FjX1v9QX6r1vCy82WcST9hkXRjaoI6hy56T5bWotABsxP2f6B34mDLDitDN+L9It/hx3k/l6j2LboOh5U2G9iHIWX1KnEvMS6s7fa6OK1RtOzSnfLmhnEBuo1Ao1uVvG71ORznvIwZOgTosYOGbqrBLm1XRiSOHDwezAykQz6t3Jt9hjWXkuij4ERpmf4op6ioHerGKa+KIYjqJ026GBB0ymKpqK6tT9fa+Na9x6oveiVpxjO6hg/3HHSRgs4+FymjBCKcCRXg0b2fHkxWlJsGRtePJspXVXnKyOKGxbPO/mRG8/hbF2s0ANSEdPrC5NWp6bYpU6zhmuHAgHC3ARghPzsuBr/Q4fHTLpCFo=
  template:
    metadata:
      name: db-secret
      namespace: limitless-tournament-decks
