---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: scraper-secret
  namespace: default
spec:
  encryptedData:
    token: AgDD2duaC7pALqol0VKJ8M4u3BLTrC0mjWBNb4IcQxU8IigbfT4DmNFVUBsL9PywVJ8nQ1OqL/RoViqHqBUwtsE6HV+osQr3wcch8covFJ9inDRPARmUTvT2TE6F7V07yxTPwKUOfOYtnQLHG1Uiuae746/ezobWfqyj/Ic+m/z7gJhZzqF+2i6bJbtDdnZk1JM0vx/ZUzyvaazQWL2yI5js6CRbkt8vMYtZhJpg4ZGhIs8U4psdpuS4OefYbsBmA/fYyvwdluI9//aSnugZFO8dz828T729OxxUhEGLNraqBZq34bDk3EBq9zFE1Y/I3qPrZxEn3RvJ80LaLJTN5LhhcseQDred91wbjvOBs3Atdec0suIUwNUGip09G0EE7HVk0sBh9mlcwhfTdkkyLju7M2ra3x49EN9oUk8MNIFxg+HEevLVN8fjP264mvEEQ7isbHWb6WqQPDPrcFyxPG5XBzTSYHcUf7jwsmU/ie/t4N6rWAWjJfw4sZXVEunqVEWwRQoKjgiTLM3PA95/YaWzQvn4QvGJk5Z9qHecxg/uZb7h+sVB5lcE8A4XAXReGAm61/yPmizSDSfy74QhKTckIXCJ31Fpi01jtSWd8ls5c0EKmmLWtJ2je0BO5jZ+iLVm6l+BdwFEb8BJJ+DafW5JB2jQ0yNhHBqfdLFiWk+AZ7qwUmtgwYktejdTrC8Iqaq/KeBQXI2tezcaoDk/GJZoK1Kv0uBOEb3ruyR1gYg=
    user: AgCxjTtBd2VFzPMgB4iMk3wjMZSYrmXfGIpHAsNow8cEFJWTCmtU1Z5HDn5KTsSNunO2TutI9i6ayB4ChuaXFlAD5wUKoEO36ExQ5kM0u6eij09o1icUOsqp0ORWsOQD+fq8HY87co9P1OVWArbIBXtanovn0vzid/iIPIm4TV8iFREaSfuTC1GWdgKVTwxeI8kX5kees4Y9mpX2C1Bj/I6+0ISKXNAOqlW4+p/WUF1lrwio80QS0vkDZeHhmPv1XvgnhP4vG8o8faPnvr0ibaCEDpvNTQDdZZDaH/2cCMTkSQ2ah5JOWbvkdr6lvZfxgsZOR5X52g2BmgcBls83QgQ3RcVZYYjYXFNJ6M4XE9bs/uFH5uDytfPmWPRrJD4MhAfdqho1nuPMrKoif+pxmyE+TMcD+an2Bp2GABPMlUFKoTy3bEWO2/Vm0m8+fxwDPr1QXGPnPAftm13b7KAp9YDehGbdf0hk3j26Ik2yC/bp16sWDlk7Q5GGwUN5gLAUbkJp5Y2suOyPhyB7MBosnqgi+5YMzL44cztC9w7DBb/5Mq+14TUEH4lsS/qFkUKK4kbb/y+/gY33BCOzFu3KUxWMmyEAetRkXuE2YGoHMNpYKZG1BOCMHgwiptAxKoe461fQb5l3wginkvCc7AxW1DNNnIAAXet8HEW70v4q3wN/+VOYIv9MetFIhECsrmBi6bGvURyYl98BsDHbYYQwNgK7b6/xPtoBFVSgsRlSlWQ=
  template:
    metadata:
      creationTimestamp: null
      name: scraper-secret
      namespace: default
