---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: default
spec:
  encryptedData:
    secret: AgBGpTImMhOSreY1tcvbVQXD7RlbtjFb0RjpyNmIyDuoSsZpwZjnXk3sd71Xs/ac3qttw7SVdsXPHQnUvUpCE3wmNcy8i9xrK+5t4Ee8pBRb5nBZHdpZascHx4y60sp769q7UCVdWJBMR5939+sFxCJqjmOdwsuIHVpI3r3tLf0eEOhOCcm3AYo4moXd/QImlTjjYXi10YR5v5I+LcGPOkJfJ/7q8GK+0rZ7AlWlX74RkVhD2lZiNIX8IMBMkcnt39vPD0nzjp6fTeRdBd/sDN/70ZHrgKyBmwNnKlaDU+/qfz8pFHRtzGfQwBCV4xsEvMwRxirQpIU1/pEVXYo/Vngv2CQHsdqDsBTA+MSwdde8RNCrpUcbVrJUmSyTIVSn1Lu5jW4nShuuflnY8RGhi5uLrBuzCOLYaZH0OLfe1/QL2LT5HYivNIIW2gPx5ccnJS5ce1qlP7gMKbg6YypwTwnLh18jjYXhJ283z7H85iTlS4KzQdr9zkC27l9YGt9759nmxMjQcHumuLt6hOS9tnJlgPDh6+xEPS4G/6blP18MH2bO5yDLQMIHxlwHXnJoFvNvBhCXYEEarIVpraZGaHL99eByg327uY7tu6mGg/NVjc/qwixpLQpL+gYVeWpaAU45tAbHwiYQpdrknKsBMtAaRIEn6t1TvG/PDqeojMKGimfimqGpmVIsIbMU5E0EMprgRDzLdnSsRWVFU4fSK3UDPUEadZDNph5+9E1oIFeeuwxwVVZSU2Yl0IJj+6RMUcAFt4Wn5LAPqU4JJZ6Z1qcf1vaMwl74t/hrMDnnbXuBl/ooL60zAGCbRCaCscJvIEQMlKRC5fCi6R3TxmafWfM6s3T7d/1DGORikQH8sMZdfM1IrLRAdws8XrN7XR2dmjkenWsEFjJ6oQN6nyyAJ4ftiMhp2s42rQeNSA+s/9bN
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: default
