---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    credentials.json: AgACkWutmgQMskC03nGfqueQwzAafE7opcfB2vrV5Dp54A9jJYhmKofQ9ZHwxyo+eegBz4ERL1UMBoApPDzeeZojxp0jXWE5DDfEW63bQ18rg0KcwhQwRSoGZO6bJFTs8c1GW3truSw+LN5/P89aeL9yAMvj0ormYj0mGYaLydM9Y3K7JuKKITG3lKiv0Oi/5MnzSBz9AS+Dh/jD0GMlTlF7+rZ3A2/4IH7dpKMYC+8DrDF0+ThcY77asCcoMBxcBI8MU09l/JTtNP/gVvzP6rZFr4rck/rv3U8sMxZM9en0XRNK79N4iDlqmCTVpI1PeiGzrhOHzVw0qblUk1ulWrhC47djn7mOoByPfdQ+11dhkBlM3v13FNwHEYAXusx2khk7nuFPi2SU37mFJpwCduXUdKXZJmlsDuSkW962l3/pnSKvrh0H3gNfVtydUN4QxhSC3l1Wmu69zIP5dqUoLbEK2d62f+x/tRIp0t9ikwtAvIprWWlh0zRE6F9HaGu7Nw/VxBNlU/s9iKZ7Ar/xKr3/4BQACCeP0gdlE3Xa2ZKaU8sciJlxX8wTOwlpbGnoZ2t/dQwjepK5+WsG9DGPANE7GD5hdI7M5DVxMeRuAv6iEsjYU79QkecuRvD0WL0XFdSwTP2RuMarhkceAB4RE5mVLC0Shh4jFqupXOx97CpWDL7GjhfpvmQtHKln7Y0CMzkEodknEUWTEn63zjqGT1eXfC3rot0mWKtBoW9ucwT+7/A5LwTJcbQ89kNOF6tfDmsNhLK5yfyPIO8HwncivNKbvis5j04KkxcYX/uQqqt8OfPs6t8JgDCyLbVsfvGktaVmCiemPrfO5uw//1byNKUzy0980jW1pabI8v0hMbTPr8VSdysFoYNCaNUGq6meuR4avKrycuCOEP9jCaEHrEyMqriRR7/v04BOkgPv0Hia
  template:
    metadata:
      name: cloudflare-secret
      namespace: cloudflare-tunnel
