---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-secret
  namespace: tailscale
spec:
  encryptedData:
    clientId: AgAXbVXHft9gCKfaNZ0rk0KdIuC+jXb4TbRmQkx7csl5aSAvpO1kFYR2Ey3pOmBWohI5e8LSJJvmWfQ8suDSOinZ0Q7dVfWzyAZVKKmpfrgwFlO8D/gJFOTQVJvKZ+3hR+NdaXpWhA5+9L5wn+RH6CV61boN1pqg8pwktRFr+LlQCxqfzR/tMKwwSjbnNI91BbKIKDlLun0RSr1O7VOHrXtIcGclm6lB59f5j3lXJ6nPHCI44NPJdWpt/7ZWUHmwOr8IYhH0duarVEIjEC3ewRfzRcwodErG7jx+sClnbhqTSYrDJFdcwMBWGRq2IQS0yW0EEfSi8h+XrKnT1zFp1darZRt28zipXdwUt/p1mj72Z3gfAC+P6/2XV7Tlmec5bfBIT/PJpGg6kAWPAH5VYC72IK8OBsoCN1S9g6BeRSmrSHKdbSeqH+bo7srv69XGEpaqoebpQoIfl0RGbNuAXPNOS/nTfTTjcMunanTG5caqnSiat/emOeErzhWbtqH9csopwryt7QfC27zcjLtqt+8ne8zPCiaY1+1SFXcCUS78ubyFJd6yma22sV4u46nmq0OCn1ojHwUKsqv9N1Iv7mPcbQMHgR7SH1febuRATxKHmClofnLPLqnktboSOjIysMV1vYes7K6JVz1hNQ0p62zZhc4yJwavmhs6Tm2Da03OOxea6tEZ1OZ7hxX63nK9KxCuz+a2tzsfndo2aADMootHNA==
    clientSecret: AgDH+y4us7OHXRC5gDKZra63LHD0Tvm+xrFgRbvTB2skeuPmFXMnrEsb2AcHzrU7KVNW3BPf2nA7t/XA/T5sNbYHgrCtcTeLz9d8ZbEhG36rcBELTpKJOVo6IlIWUhXaFM5U9nqa0A0P8crDsVFbqX6pe6RIQhsKDpE1Yja/Emcxn2Y9zDr/kAwQ0gxxEB4Q3i9EMoN4e0Fz1lyxTkLaJ3tqdxHFHrLOtl7QchkRlsG0HIle0Xt7+hizrmFh00PGCPMe364uqskDOL+jWXaGrUbtyCk+FUE0V41drN/Rzov06kO4dUj1G2NFV3opDGeB7i0aWWWVXKv4H376tSX3mldSWjtD/c4DRthVugw9MOX2DrUxDWXYgOQv4UWiH3J8mbcaowPDA1nRJ5Tye9Xix6tkko/7A2P8lXj154CYIBov5HNNxMiQj+v3EOPxyjbc3lz7mX6WSXHDQWK81qRjrlFbyDWeACVU76uQIGL2tiwk3qIdPzu6eQT8oHXTFRG2kz41AAqiE8KoCEmRBxSPY2wOVqDNflTs4WHMeMb7pxWNESieoP1I/YJJ0mxbGr8w57BrJOw6NDZ0FFyE6/5/7wW2uI/i36CIlnhgSvHfYMgcS2XzXXwt8cA9dvVpuKXbniWYqHvDt/FBlTNC/JHZM32of0zLqk+nHpNSv1sxAj1htLS/IPgzbnyfoIIaeldwcu9DTgBRU+gaYqMmdxi2veF0k2Tv5Cy9uTZHBHLvXk/T6GVsuSZHcqbmGyBfECtscUmF+VWBrH+4Vpmvuh6gqkA=
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-secret
      namespace: tailscale
