---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: db-system
spec:
  encryptedData:
    password: AgAIqQbEha33t26h3NP13F/jTUKafknxAL+OyZLFTjExrsZ/V+pTVjl8t3ALBtzLJbY1AzBz/wdU73jRW2hoKb9pTygIgaMbj7LD5DtuZ0SrZpbhKI4j8N9EiRInZxeLk0ngF2AUM7ZtDiGQaO8oGOpXoeI4PuNFfPL+RGOi1FFr91WwGLQwMWG3y2u9SM7O8lUtuaTF/YayKggIpnZeyMB339xrPrEzFNgPa0x1ymkqs3Xw1MiB/Skng4TZhaaxaG0GZQNeNjvPJ4V+8dfUe+dG7EYYNShoFF/X9qi04Ymjl6cdDYH2Xb+MG98UH/M3fTfNdrd9gENS8PAgaec6BlF4VghksxSyuv2GxpqY/J1Efqx7yZZsp0+PaKsVAK5iJznyY5xZQlxjbZCv5dOVqm+lcNylejC1MftGb5xQmUvIi6ABQVf9k6qyB6bjN9CY098DgF54Wi1uGO/ZZrCyZN1eMvXhwrQfRRQGX6XxYW8aDq5108eg/oIApfG1rtltctQXVZm1OGUzVPLbwU/xxIuEd/EWW91KCx6cxIjM47EKlppwjjTUGiOWE6mn19F6Tgfm3m7/xg0Mz+vUyN06TFKYWUhPbOyaffKXhrj5FoG6VlVawse5eCFwskjn6uDyHqkBFaGGVu98BSx370OC6MnDj2Y7ii0jZFvL1+xUN67LB5YlNquddD8ohMmSDL3j1y7J9BMPsRSglssuFms=
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: db-system
