---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-secret
  namespace: actions-runner-controller
spec:
  encryptedData:
    github_token: AgAc+nwebz4mGKh97673RwnaVPHnfaDMRobLztEdr77Qw+9t76T1VQpenxWSiM4uBBW3KD0mANTNF2wFRVOHNWIRAJ8B40ZCSlAuDOv3huv7zkPWspHYaZo8VEMvPnlAOdU55PkNsh5QUa18pv+tShsiAUPz7I+CShnF2vcmB5++rB8hdQMKEhLZYzlSf++6sxPVnFSubEjNB57m/WwkfQe+nuz0rMfqNWCzHLyHBecq1JrTqagrzbcrSRZUIsuPHb/CmMWKK8uqWMe5DuL7S+WRP5921ynPzaAoYkEj2jrOYr/F/rhggHfLzqPnyWtJQp0UgMQaYwCp3QL/JUNwFfyQYnFv05E8PSt8QwCMfRPsNVUcwfRTH3PkYpmaJetz9G2vKKFuNTLAnorROTRPtKzlQLnaOW2r6Hn5bR5Zx3xLaAtFzAPtvm0eIpCk7K1ErIIYCE0awPotfEs88vo4i9hNyFJyXG1klj2K8r9q1J6JP8wn4UTxSFGZWwh7bCUZek3bNzwi8KsUqYL2yyESiyK1+MLgaPHMDTCHfNswlEME+z50nOn4Tb89lglxyjUVOz82jxXzzf5kszNcBySf2oT2mxlbxOnXW3hDi9nD5xHabWTGF6IYotgDIOyu5DtKkOVng4/+JOkmqlajWvn30CdMKAOGwo1rfvlS2nQ5AuSEYVJjEFZ+qtKzJuju7aYFOJ2IS/ACdgD0fKLk+zvlXvlJPHVWnDdc3mo75X7LxYSN/xQ4/tQC7RqHyI+DcIoCdYqcLQqHfhGN0hhM5Xnv1D+P3GA/4o+yLxD92yB+jF54cITyOhF72g7qU88fIgM=
  template:
    metadata:
      name: github-secret
      namespace: actions-runner-controller
