---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    credentials.json: AgCfKdfb18s42ZZ+dY0OLAjeoHnfqeUSM45qMAL12mx33zPWA5X/Ca0cmS+m7VvVZGxBfC4OKUr82bs1f2cPkdEXIhSEk2KHmM3eG00PwePerzE0sR9QmCqpXbFDPZVQHY5bY68wJPhS5+TciUi9XEePk9UGcWXASzoDqj40NnqeE1q3MEZdMToKnDaVmOFQwwVB0XR7lCMZKoqMeV9+NIZ38itykDFQAc1Ku6XGLbMfhtk2ilHa4RpSjxTH69gcuZQGNRSiBv9I5nYZ7C9zrpYQamIDPfBZMj5MPRpQEkgCdI5FHDjqIcxMnEi6w/wUUNLMiNtm41MU2fFRyDqtRkuGJxRLghIZX3AfHccB7vf6ZZDWNQtpa8uaB3ffOulDIxSEci7dL0OP42kAd3sNUsbeXUKBGxrClYsJpFhxaEgDbhFoV2B0l4YpxrDsKVpzVwJOndoHQk4sqcBsN83rsYWw1SyoD1bo9smZVFztD3maq/g99yhFhZyALqk8mRTpmhR8aj1NnOMTWzuBwbJxekNXOiw4J82u8rdZYg5Sz7LuNP2kYtffkqHTvz5VTpZNVnESD9YdV/mOI6lzPaWhKmK1r5b0SzrFrVGLCUILqtcg9vHz7N86Bqe3qtheKVdmNRLX9RwH/2yvZLBEKHnl7Thc0gVZooQjL+nbvoQ3geXvxyX1+EV0Tcrz8y5+jtYEtCsjDW4GmbthEycjW+8W+jl6/ELH5PoKnk8fcn1GHjg4kf7P+8narp0MBvLsiTTSmJzHi7FNnzpskb99rsduixexQcKtfcdoQT3Y202c/05hVnPs7UagY4Xdx5GwJP7eQBGDio/2uvNvuyBQilB8QEcHH2wQ/4+8p/HAF5trE3Sueiv9sELQREaE3cJpR5gyGShprt83tbLXWt9+XxSX9mEx7kSM3heOWAa0Ls0O8Ftx
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare-tunnel
