---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-secret
  namespace: actions-runner-controller
spec:
  encryptedData:
    github_token: AgCIp6z5vOphE3iiLR6VX08Ym7Vhr17KIennbOkAsYuHxuq/uVwDYyzNE2MpkQvX3NrUoZ34SG8PKR0d9FuNEkVgWQAF/hoDmGtGWcbilSa9zZNP/QTnlE6jPUtOJwTRFa9d7CFxIQwRLK/TYcPcNqJnIqY5YmkOQ4r9/0Tjw6qfAZs7hzGIenTDtBZqeHSDuj90WioKEGg7cGLg505tlIkDNPgZsdOs6qUsl8NMatv2ZfDbnoFNuIbMWoesC5AV0H/WrvLzKI79q6hnxyXhJgVFtFqLuewxswafULd2r9pUo97BTcQbthI57hyXs1IauDwow+FMSincBYB8AjEuEDFItnV9zCHwWjwhSYQnOdm9MHFGLbuzY7WagPLE8LEHbh3g/0baSO6ii2cuWiSoUah0nD2/1dMHOytszEASbiZJ07KRUxlR9ifGp3HGtahZOd7nyj6wUx4LcTLHHhwt4+eg3GDcfsBqX7YqrEUq/RrC/r6dN7mGwS5eIACKW6JrRiuBs133K6YIPXCF0rajJykkqAIogYaPWFSwJPyvW72941Qe9k6DX/hBOnTQ174hjygyVMO2K2YARyVHFmQesd8AuWGwU/e1OovaE+jTsT66P1eo3qKtHgQKJ5fljA1lHLFUVb3IelNZi5PbN3oGTQvc1LOxM71tCjbVu8nd1+Y2l1GEeKk0FIkdYv5wAvuNfo3JaK6EkJbxOLqS1ghOsZjOIrolNMPW0fZB3ID6nOj7H0gZ3IJKsaI9DXjMoNxT5VGkznbBe3jFKZldwhxazC6cv1bLQRrEF6Ty32D57G1zUUD+4zwioC9o495yWeg=
  template:
    metadata:
      name: github-secret
      namespace: actions-runner-controller
