---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-secret
  namespace: tailscale
spec:
  encryptedData:
    clientId: AgChqH96araC8p5Ua4HX4eyFLP0jpsCwTzVzb6m976jGjxltVHtbL8nM649Gm7XzoJbSLXS/C3BQFiOF5BeSj65z6h2NC0Jxf+j+2OexH0jR+HFaazwL1DREaaHWIbdVPPCVdWgNqbwAIlE9Pc5SsKjXt84/LYmQKv9etnCqYXAsX/Oupmkfn71S2Duar3hRF0dw133uCKWpIT/hKKgvZ6GWe28DvhCOj4JjbuUnaugY6uUfBTio7mCRMmeUgsFWvOTFhfcJdr3mlyEa7JWLNnMnBPk+i/Cp9zXOmuUD4WVj30elEFr8Ve94YNK3HZEdoaa28mz6bYnkrfb92ilGV6UPNDXfPFzN0iTKc/mun4k4zf3BMT/aJo3txq6xnYMVhMqEP+I0q/YbNQogxKOhyyiIQefejEW+wKrT0iSP0dlKxgw0befi2x4mUmVHyNXoErfkOJmNI7ErOzhlkpqP6JPi+9kX5bR3deySfwU9im3PoPjTubcmvyAMnd5S3+xKDDcs536NbKNAo5TSax9eYCX7R+x8cDicsipeCZRAz2dr3DK/Vov7CA8PTracpw58eqTju02cZJDEmxeKWf36M4rb7zN0O0Uc6+uED+Cm62vSW68B0kni2VED3ePMG4A8xiHM6BUTZ5gn73LYm1dMLZh2ftuly+jBUCdFGWIwYU0hiyOCLHZXNJe+Cskl+MS+Jh3giiT2Vn2MSoI8lSwcEq5Rgw==
    clientSecret: AgAf12NEr5LyAOvTL/Qquf7fBW3DbA8fDLV3o1kV38+e3AVHDRGr5aKoXiCajlAu3WVz0lvoKaMyojlmINakdKJHO2At28UTNpUIzmeUsd1WnfqMasO32kN0EkYsxhFbpajSu8BcQM3xQkpEfIG+K+KeqEPNgVDjRnDL8d21Rw5fSuAmGQF12/oH0DHzDlEc+8zAq8vyWpDtm3ZcvQKyi/xnxxgl5Mdh7sd0ZSa/4k7KYvNFDqcjTZCj15fHYDbYdpDAadAttwxofct3YLxBM/S7W74yLxdAHxueBNGw5I1j1PtxR35tP8JHn28nhH6J8ugG2MabgHU4WgG20FIp8W+L34w/RB4y4rxl0PExtrfr6tx5JUcvHQv31Mn8KgmOsklGvOjFYnI4YEAGNguwsZ+qp9wQ5fwGP08q+kAbXaIbqfbRfUT/LDbT0/nGCBTVDa+VKETfJFCKUzpaZRd1+OPROs2ZYEN94Q6GZlDtM9bdaOSF3oYSfcXkRhwPope7Jblixmkz2u91dWhYeikcpe6Ewybm6nH3244BTkCKV5u+TjNsd+WYs+mssB2da+UXhSfx2fmT4VgDo7bQ6v9iGyIM9VhupkSUvKxZ9zm02vGLsoATYZnksw33vDZnRBoW0sxZx4zAdmNkNInY425a87dNRP0/dYZQXAN5b9ScdVnarwAs6PQczW2tEdR7Rt4SArhDmazdT8+nokGiPdceMkbU/hDl5oY/uF0vZBL2TzXRvBOnFtrrUZG3BQdI6hmrNuIU1SP99msGfEnwkQiPmzE=
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-secret
      namespace: tailscale
