---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: db-system
spec:
  encryptedData:
    password: AgBA42rY9lbi0t+AAbroZtRpSmoZMVV3vA+CR22yfl5X3qABrPTchElfRRqUGfjbrVxbbvGTTIVs/Q6PK0SUhnzD3D2bSwCOOX0BAjIyLNlY8FQTOboHTFBcqjg5ZxpolnTq2qV8FHT4+YU+Gabk4Z0ecJfoZTpLu1KgFZsH5S6wvfd5p9JsCN+GgnoIcN0kPfxtZIo3Zjdo15BT2XD7KpwazwIsg4lEyiwAb1++G+Ni/pBn9i4LnpU8wjZci3F7dDaLIntXBBfLknLowFJ4URYg5swgeCjHURiv6PRx347cTkeEL5QtrYgmpvLtF8p9nxTyKjZCrS9MoC1fe3tmecuz3n7ep1rpVSiQs5Yyvn9kwDfscQ2upxntlDNqZHhdKS/j1Q0XPsz5R2D09K0N4Kb7SVVxSpvi0fT12Ky8C6QFIrcuXV+eGsS18So40o8fH9hCGR/fzTrciQIUvbGWOy3abTb9DG0TVhkXW4J4IHwD7ShIKN0HUypp/VueoZW8Vv4PBukm06YbT7LyYuUHBUKFsDU2VodrYAJWRO8BHTgl7MYgheiULaLKjVkeLZ9pNsAN/FSmea6Z/qMhAkgxRLHBJZ6HEM5Fi7J5B4XQaPsU/xUT429cihAv9kcQI7qen9x9BPIJPM2hV9bersLtla1ydVZlYIrhIMzl5JY37IMGihZl2OfbolhsN2dqsMq3SsSdse872nT302QSJ44=
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: db-system
