---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-secret
  namespace: actions-runner-controller
spec:
  encryptedData:
    github_token: AgBq2DanB1lFA/D1hVUy3JRH7XTvYaf4rEeYGVxhAQQVam+GVanrHI8mhQP6lHWOFQ0tcqDAcVCNVzD8cF3ggfiVGgiWzrR9xhJmO+tiFMl1XfuH1YT3uLxiEm+Y55fZZU2feer3zUBF3G9QAhjPdc86auZfaF9i8uzA0G2LT7u0AgwcgXkZEPUh+qgMD/Rjt5siFX7e5nfmSko/2cIl2xSfdxLZ3Mx3Onouez/pG/CnUygmwYKPfYNL0nyfWgV+6puFf32ankY56HuO0XG+C0cTSDQYIVWdUeoZ9BT7sYskn4jFXvFkwYZ5YgnglIz/SP3PWxpW7ybC13YFCDZa20jb5O/8jdyplTrrZNN8bnHRrgBNlcbVVtV6sYGg0aFT8DIKtFJzWTa5GJsmaQv5PAPzkOd+6FJdjXzQQ6zpfoZQIy0vJWV2mGWivMngf2OzjXHLHK7yE380wEomEZAsmXD4VZuuVJe4uYW8stf4MYmvfg+en78vVDzZyrvBa5f6DLH0pa0zrRk9b7FnF5BpPYyfmKgFlC8Lmrp+YQ4n7Sc+gld1nXI9Cb0LQK+5l6pnhXFeNdk4nqMGIjQNWLyl85ZNoCwslKXCHd/4iMhCNgtm3pH0JcijymJsUfmZwq4pveGvxnrRfKZuq2CkGJtYKR+W7uujnG2zyBvTGyLaxeDKavQkRLk2oLHzFuQUkZd3+4Puyw/bZ9XBSpiv/cSCRi0CbEd9AFWUMx70+QIbNG4JxA0oT5hpc67y7/hr6Oic8cTkgPKxuDGb/2Pq5GPQur1xqfkFErHyywtDRxsPRo/HlIrHasZWUlNB6LYYiE0=
  template:
    metadata:
      name: github-secret
      namespace: actions-runner-controller
