---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    credentials.json: AgAEXwAOSfJDu635VNq0eVrAJuY+ca/NwLl4zm5Cxl1mssQMPBc/Z2gRQKT3BD5t2IlojGBjMkOkUVItSaCmD99DrJ8OOLs1EBvRBd9XG6xcdolqVlT4mxjWS4soNnkJArLhvM1qCN3bpkLEYrpc2UePSytUVKctDA3oSkJVdYtVCZAZuEQtStGLHmEhU1le7/IvFlZoRZODJUTBB2KADgkNlonaL6XCsIUiNDkNQM4R8Sj/WCIVO3+GJ3lhP/aad2exO4M/JcvspL/3ERk3Jjo2sJe4uVo5S38z+ouZ4mkCUExRpHED/zqY87fiflz5MsykPwVRoKHdOxu3PvrlzdxDuR13F3tSSiupcjaW2c/zEQRTQn1X/TEAD/MeZ8Y0ic0dl4LqgMjBc/5tvaqvYUAcFuR2//8IO35kP8jqQBYQz7y5bxX/j/ioLl7ppnFQIxFka8aYa3ng1gZR7+GLLSWd55LxZmLEjWDWUjzRBBUbu9ofFZ5zohAVn6l/sZYZnlckkEZ0ACtIMvEGxGYK79CnF/zvcMMZenzlZfHPhKDUL5z9aPn1bXrSkiMzeWIMmhjezxcb4zBsvJszmNp/5eBj5iy/nAucSGtP03S9XheS5CY3eLccxlO4W+TC+S8PBm7wmJT92y/Y5CypOYAIEk8KNqSAwSbcJGqoOaclMQ6yn4oSU4RkKhB796QvC+hjji0egHI0qNirJZUfzzhnbmEPTAZO0PMyB0iZnDfX6g42gPPVIi16mnKK/x2G1TQ99l4dBbhG44uYfE8fGI5Ila8sF6i4Hf+0jnSNgtciB09dLvSLCSJjAOBXUWKey86v7y+b3NcU+QFw+Z/3GVQZeujYVnWGvBi6oJTlHIXmBEtQromsvDVXANZjIDHaFfCvuf6lau2ZCciZ4AIPZtpSzKenPqgexeohYQ7FZauM+D2I
  template:
    metadata:
      name: cloudflare-secret
      namespace: cloudflare-tunnel
