---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-secret
  namespace: tailscale
spec:
  encryptedData:
    clientId: AgB8D+eQAqAJMWgO/5FnOGAQDuYQaaJQExXhEKoLrJd8gSHmtrayScjABsClBKC6//ey7QwAgp6KDCQnMntxxVokyVcxKV0wVUKqOruWtOTnJjvReVfFRzS6qXpuJRBbLbME1QJ0RFvfRyVDbW1ITWt0dSK1XWkdcUCTt44IOeJiaZmlUiioZyiQFIDowV0zs9SZ7YlF4/3/Qt3IhvFQWsw5BGcDqFO7gvj6f5eDHCwsND5FPUWny9Up+0EteNCfv742czShIZ3HcAY/H0MoKvJSMVIveCTCEMyUT6T6//Q1JWMr9q/s1UmdKsUNnEyG3M7exrkqKzPvnCDBAaHFEbYLpHLhznq8cpx/dvxtKb4UIZbYvvEBaf5MrXQTajQcNgv1fynHmSPz3tV31bu0dd05M2LnMrItZYA3W0um+XGuBlh5qYr4QaKVzkrXHXjn9R5lcCcwn6MUD4nzzz8C340BXX/2Hc5MMsj6kJLihLtMQV7+lTUV0CDYa5aUr7+RyfW/gcXYoZttzWAWfv1AKm3krj6WPGbNtAMnzOFQlTTyH6D0/qWgKJJP7i8f2sDakIyqcUkys++QdpcRBuLGvdrnewKFgdGV9GLsUxJm+wm1cctre1kSf8avtQv/PuJb7gdKUQvqy2Lgdo5JBPGIoGN5EBrLCJzv3HaYm879DplWsxK1HzoChiJrfq2sxAJtz4IqoaFuXL5KQr3yEpBdbPzrXA==
    clientSecret: AgCNKhdALa4mnrvX4CVZG/k1Jhnk9oqqj4GrPAC+Hq76jpKncColiEtUaXgz+3kxzNF+HptM6lHz2kJSZUmWX7HJygN6CCdIWWQCQtdfy/a9h2OYbJoaKsE8yNeOXVKpuYjgtVOwoqQFVr9OalIiNZT2Pj/l4aDhTajpf57QQwjY9NinW4K9gMlhH1LdSZM14kf6aFgkA9+sN2XkG5EZyrzgYslOAQ9dGdHxEeNaAcS0HwSzbxJAEWvJ+H5rafF9o4Ks04LFqdLdxYrLfhNUdZBkirRnDn5PihW6jZC/b+hVtvJbmrYn36eifaoPRz5vqeP0MyoRjOTk8TIk+kYDhYeva3RaOwYRmPLi7Xt4hRa8i/kNMvrvCt19+tMm8SHXohW/eafF3yVUH0cvtsEiAoNZ0iG0mggyy2sKAtcvipK4QSPan3pSA5fIGYQT4Oa4yAJlRRPYXoaX62SPk4Q72pzlIP6bNFJyV2WmbbIwMljBKtj8x5G8dw6CGCx9koQwGQowqNkF0xg0fAT0Iupi6pdCotq0vMNZ7x7xfbOQAu2SFqFFhOyO6jnXJHAq9vZ0F2neREmjfCyKd5RQtQtOPmwjT95mx61OP5Et1uAUYI2Z0sCmpASkMvApcx1LXWxShA5cj/7iPlfFFifuq/U0NWEtz6ss1kl9PY9/kYFHueU2we9PLPkaZPX4PFJJiuw1Rt1mVXEWwL1CYgPQVR87qiXiobw3E0iJ0tljO4JecsCGdWg+ckzmmyIxRkLffOYOkO+NbjIBGP99zs9XiaEzm/M=
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-secret
      namespace: tailscale
