---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: limitless-tournament-decks
spec:
  encryptedData:
    password: AgBcNLQAobdMN4AbGzM7kX8lqqQzXqBAy8qAUzLVAGveIX2EOuSB77+ssWpH0mW4jTfmZiakYzwEdyJD9QYRlyoJZHWjcT1eeXHFDmKuDbsH3ElaecvVZi2EvkUwkiI9PMIfrizGLRIX9XnzKrJ2+UUtrg7/eN/aM8sKwTJRx0/A8YcSUhWB66b64hZaTkMsd1FIY+N8YihQoo0cU6moZX9CJdx2mX6ximsTyiCTVX6lpAf0/MrDfeGwBl/ODTBtO5nPlkXm331UhWuIDg/dPa5MfXizPLz71r3gSGLeCWO2+cMhJZQ7EYSeMYXUWYfhVuowJ/M8A4rKcSH3aSdrlGzJTZ5jDWP/zI6SH3NsiUF9sMnLhuEMP9MlrhrSE3XhNmagnw3mhpFAH8EH2Po68iC3J/SJiZ2lyXE7D7OnVpzRDI6TF4+kgnGP5hYpS8hyBZ5GWtpt9QQy35x/K/723nyNInk/oG/wYetYzjQjUehfqh0NHWWjrknavxla+oJUeF5/boQVF6aWhHSffGXdr/3dEEDthiXTHFj8mtmv5r6wi4ybOXUeg1ftb69iUwMKOABWU5yrqPZ/RoiaBAq+t8p21xxuaJ7pi45GvW4y8Tlpzlk7Z39V9yM4j3aImJYpHjP0LNbyA82mZ1UzGlxTQOrTAe/enAZZnGjfYixKnYq8lalCMtEDXNOfbwp3WA1Gu1O/uQCTSVXgwranJjI=
  template:
    metadata:
      name: db-secret
      namespace: limitless-tournament-decks
