---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-secret
  namespace: tailscale
spec:
  encryptedData:
    clientId: AgDGr2aWjp0Rt6R2bgnw/7WbUJ0IoYzyhiLWbUDZUARrD89DtsYtn79EBpAy0Xzswc4K7nzJQOoQ0fEm3sLgejWY41oyxbVcQzkfhHnluVKj4ShMqTv2HSPFZ4nHAAPTP7XEWCUSS0ay04zkYhX+ZchL6xeMS0xlGR7eNLuaHLJD5YVt5hi3dSCipvLNoUFFmGvODkyz20Zi9hwAu0N15aJgP7ccnbgBJJFAjMXoSimWkENqSzlH33ufjFbw6tIOTvzMg5Pp31htWsWKRHjFt1QPP9gK2TAkLL+sFtJu0Jz/V2v+5PLeyxbk3u3F1lRSPCH9KBk+nd1XTQaDbIBm2de1sU6vbxRR7v0InzSS++BO2jBc8me+2+q7tCg2kMKWwfHqcdeAjPj0URWx4ZDA3Sd7a80pfngP07WkSUBhS9exYGRlzl2lLIUyoZpetw916O2SbokvB1s3uzFpGDs1kKZSb24YkqQJPD+FQ1jloOehAGIt2cmbYwZ5KI+d8OXh4756ZZ/VmKqt0wzn7YqU5/8ULyXoHQdSqpeCGYN7pX2F/g7Pjiq7hyrCyPcKkeDw63ps1TYRMZL/2OiiW4vojyaCiZ/6JzNL6YKST6UkCV7M6+f0sdlih6fHiS6iT8lk/ZP63W9IINTNYG6/mELUsAEHDBBdnJmL8P4SjrFNLoMokFefqr9uoGQ3TBxlIL6ogXyPiWp6+Q4B0PIOyy8XlsQARw==
    clientSecret: AgB4A0wWO60WVJx3yQWeduQqj0L+AdmMuR+UOYJfkskEBQuSJ0gPrd10AnXLA4oFqb+yah4mzl53nd++bTH4lWAp++uqyBbYGZjR+mCSMxyQ0Cf5RCsaXWgOt6dHZ8mjZgGoKu7OgZ+/EygNU4OHWbLYGqKLFG2pAkkva0CX3LvOLGlbVfX62Gi0lPj6Ljgr5dxo2FsOmDR+MxOYQzfWsSKmOtTUTHVs3qyGDHu3YxDyZwA+10Hy/i0ENesedURxjoNMlH641UjUXE9WCsPVz16WgxZEU1o6GXOgY9OgU1iNkSa2OMEfi4MAUCEGDomv0/dE4cSDjl1JOooAicRX2TF6nDv8AJm9k6UKXEJIizzKMhteALtr2rNCo9PVM4GyOLmgAUhC+Vb/Qsd4lY17TjhteRKg/1gkqkrqNmiV0uYKoqtAvzUct0hd/s97hnvGBgxHySazmP4h3RbquBdwAUxzAJW9Gw1GwoRWJ/jljAYxrF3aPCHWTfcSFMG/onk2KP/bhEKZkF2M4CBdkmAj8mY2omCEy5Zelu53aQL6BrjHkmI8xJ9dvc0/5kDAp+NH1GXkWC6ZSrIC/XP/hk5z5xwn4yRI2FSZjlA40uQd1ub/nIJQFbgRXhsTQG2gjGSds0rbTxIt1h0bJz2GvrevSVi3cqYJlDWl6gZl2UKnUarddCqWYWr6BN8AU7Xy9uhyYOmFTGjc8QLJPvT+umpmfbDjNsmcTM0bC1bJR9xm470vqWELBa+VfpkQcblxvQ7OGJycILbTq0G8oWWAhxwf2CQ=
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-secret
      namespace: tailscale
