---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: scraper
spec:
  encryptedData:
    password: AgCFhOAbxuZt3ZX4OJcJR+q15rhXSlOBFQAL+SYuA/HbwVVxxsCizpAake6jkssA+HUuyCvnnhfxcirhf9Vu2aO3jMJMUThu3Yqm/uWs4y4vJIcEreHxx7iyYYou5dbluP7m12f9pVYchepp9pTvFAUywsTB4Zo/iqVa8ZMkgBFQT/HBeTj53O9rf/GJ6zwxfgxGabNz8dP0uR1cmmZDyWHkpCuhvRMIwesRm81rKKzVY+16bvMYKn+OHV9IGMtFV+vtoiRnHb2K3LeWBUeIgcpg+h/4gC3fPVYaouvrZh7LsQsxIBlF/SUvsmkkf3Aa9XJs2mGfowtnzR9NfBLDYghmkDclHMoE80Ocz6otAvQuDpyegyWUBvnoq37lu6tNSXKldd4nVucLMCdN8iNTH4FkxY6+KPWRYGFe/7zdzpr9o+neGh+fM8faqeF7LEHN32rDaKpnmGTLhBNacvnKVo2KcmFAzO/D3O0Vk2bMVaX4zn4e0GaC1xOm5+zuKStjl/o4c/YcRxtTw0IURVhBYIuDnHzu4je+IKvI9r9CI8GafiTtLT3huND0soYnNmqQRhPCTJDJwhD5fzlUCZtEm/OhgEt9MY442HZ0I9mXmqkpoWCdh90wiRKJe+0vesGAtkDJclbKUEuRIPs+sbFU8S2WBspjYHiYto9o3f8nIuZWTwNHD1+nGD4FMavO+cFySc8sBjpEc9uFWtlIxag=
  template:
    metadata:
      name: db-secret
      namespace: scraper
