---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    credentials.json: AgBPhIG8XHDvmDY64phcfTSR+QDxRjiANBlfYSUzmN9Wy+6Bn/ggPWz5q7ldN1XyzPMJc0gB4FtDROWfg2Tzlst9ApTzCpd23qFduegq8hoMm57E+/g/FuGLvwpia4S4qh8kxjEpBkxRi9HJrfVDNv0mrh7BNJbKICVquKcocjRHZ7vtiKpaxZ+ZnXgmrtUMg6M/klk/+706NJwRW+Gs2dSF7g7ybCWY26+6nFmz1GFiSkoYIY9F37uDP9Sw6fyudAwiN/sl/T5Uv1QxbJelpFOPv3WBcHKuj4GREQzl4El6Q4hc3iu77JRGxmw6h7TuFFrfXF9BoLeEXAP2Mg35q6vUru3Lub8zW1Cr8wkZZV9zrMjkHh1dEFfrn3A+v7WTBc5tqzgnEC21XXpBZRKNKqqH8VEaseJIFq0Lze/DD5VVfihmfZA3kcEJeTOnSK61b92QPDm4SVEi5GBbse1J0E/FKhmC4vyLtPw6BHZRHD4vYWZOfgFGCmOeUyRQP9IVgGgO4aSY+NDdzThG/lIUerxlVmos1K2+bhOR2CGPJPsdjVOw1A1yOjUyN6QNRY0Yi3WKBKAlI/wSbo96P8wauvsO6T02IzC/I8T3hqh+cBEz5ZLpcqYAnoWyx+NuR6PeaSeFqwSOgw63Y44tVh6HLnll2ByHwdDUqn2uwKwglHlbnPKjY47e8Dl1L1h8Bj4al5zJp+718q8c0fw8VABrEktKQYHgc4IKiHgnRByP2o6KVPJ+eaB+yjo8epr65kohOnCHJYwPCKQBLfhaneVrpqG8M9lSD3hJb77tX4Ed/fT5rgCB8sJsTFjwcG7QWhPJXfLY7+6PT3x2bxW0FrsThhdHn0RO8bf6vtNm1hHASKnSjSm3z26rlRKz8tftdsFdtfSYb9ybtngyUrsK2A1me0Bnay0lgBzio0/21wKATLkM
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare-tunnel
