---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    credentials.json: AgBdQXD6FbWtmtcpAxdrQdn7KlnFaoJuE13QVxkax6g3VWwvDVRvYOb2d65UOf9q5Yuss3hnNEFDBASWWFDJytoBwz6btpREsN6ziaYZ+OUqeyD2rnFcvHk9McrdjNXD8rpazoIo5iJX3LKHVeJpuhZwL864BCaTLF49lBjdQgW55RIVLwLqWsJivWKpuzb/2tBc65D7o0NuD/g6L20+vtj6PwcK5mieU7Ks/Ff/r/Z+GD8B8gV2aSwnAACFYrqR45SJ0yWq5HOcvPXrgcHVLM9LbDF+lVEIgJObt8iFoGBbIMsI9hXbo0uq//JdlSbW2V6rlEh+NS/uNM68FRHkttKGgXQ5ucAvJ7qF+lih+eh7WKSUZXh644zeQ3WUq0CxMKXmqGcJUEYXi0LzKWRKHeciQDDq1n73vukWPjN7ZtF25ni1q8OtxCOJZQ4pKWiksn4K2eBvzDgM7sAvzFOb2JW5VXHpLiAB6NRrZz3DR5qC++6mwouysEpGaQzq1GmWXsOwPpC5U4h/yfm3DPrFp2Yc4CA1Uv2WHnE4Gd5bnivpdfJvH4ggDXtrzx0t8WZFfMBqkFe56srzqBCA5dwreXHT6+lL6ytaZqMbtSu2A4hHsIspbR6GbFL/JxsclicDOur6TeJbuPi9cLceOgXFEk91jnkgjXJsdWbUxjcjuXNy+LQiJzVSw5mLRlGKVO12UCZzYTqIkLJ+KF/Wao8YWMrE7/IMEuu6Z4gsexITWGusnjGUyB3+5+DqXItWwsRI1GSCtV7fU8s5NIti1x7ByFJ+VJ/mvY35paDvNoPWXq3dkyCop/yzr4kKTojfVYBfwbaa5Huopwz3KiIyCvhfuBsO+hW0MVzbcGEyN+UYxO6HMjXGyuJjE8xsy2GWkku/NR7f01h5YrjxcwnubmS5SEuhP7pdETaoWFJA3VjkWv5P
  template:
    metadata:
      name: cloudflare-secret
      namespace: cloudflare-tunnel
