---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    credentials.json: AgCHN40hy6dy3d7PIehe8asE0w35FUQOhzVbFt2R0DikDVXEU3Tb2eoGQ4pOpby1oi9FqfSX0LL3f8K7R/g9uJVs5XQBWWfShDkIZqwsm/kKw/OwVJcEv0EooZaZw5qG025piQO2CS3OvKPja6lY9Ub/h/t2GPTWPIfv5/KpHRfDnQfLOSEHYWK2P/Sfuk1wT135d4t1b94vWokmpHGelg7+oke1+xvVaPwKM1ZkMfSMLUmch7ZrqCEuejWcAPdEPkQ0Ive+lMsCGGQ/riMKfGf06yyVz5qyFp1L6DFbvhbiQGuC2zG7lXztYsuTxRD29pfXkInaaCtztYi2nbEPvjCk/HPIo+aWNh04dxm4W4CsKdSk3RRbRVezUBRXDYcMiZYcV3iHxS61lT1rizoCQhlBBQT3hfj2mleFM9Z5wPkS8qAPcfttRGdGXFDnBYqgDrtyLH2eqr/Fumklxuth1EYZptuHBQA3EedVw3bbtbEnPbsgQ9PYUhd8xClh1dy7RxGtlXOM6kPX/E5fnWOBFfjutnz/DbI1oAnL6AqeA/oCRsvYyfnXzoWuzg0MZSf1Iwa9wr4AdZJrj1Xol7nspYOilr/0RWMFOwHVTs6poaZOWA+KaKko7KMuwxdCxcBd9/o816SgB3DI8X1m6+Ls0YvqmEDaCC3hoZ379VABM8ATJ1Gn2ECUS3pXnKFRQh+YtGgIE+VjbEZUnRfWfcp10yxSqM+odFGUY2uMjo9Apg7cwCvzcDHj5sJQQ/zhiE8vD355Fx6yJYR0DpNSJqgldW9V/+FKL1jVHy664KRkOjSE2UXydO4LVP5sF6ZXvSfzyOQT9K9xqyjHCqKZySbmKt6V4RB0JAxiSAwoJDvcGsWDGXuExi6L6dPyRbuaUnD+3xKH2o5RpR4YW4dxerBSgjcjVW9mJZAueu+6hB1bkb9J
  template:
    metadata:
      name: cloudflare-secret
      namespace: cloudflare-tunnel
