environments:
  default:
    secrets:
      - secrets.yaml

repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: factorio-server-charts
    url: https://sqljames.github.io/factorio-server-charts/
  - name: tailscale
    url: https://pkgs.tailscale.com/helmcharts
---
releases:
  # Distributed storage
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.7.1
    values:
      - ./values/longhorn.values.yaml

  # Load balancer
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.14.8

  # pihole
  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: 2.26.1
    values:
      - ./values/pihole.values.yaml

  # Ingress for local network
  - name: ingress-nginx-internal
    namespace: nginx-system
    chart: ingress-nginx/ingress-nginx
    version: 4.11.3
    values:
      - ./values/nginx-internal.values.yaml

  # Automatic DNS for pihole
  - name: externaldns-pihole
    namespace: pihole-system
    chart: bitnami/external-dns
    version: 8.3.9
    values:
      - ./values/externaldns.values.yaml

  # Monitoring stack
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 65.2.0
    values:
      - ./values/prometheus.values.yaml

  # TLS certs
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.16.1
    values:
      - ./values/cert-manager.values.yaml

  # PostgreSQL database
  - name: postgresql
    namespace: db-system
    chart: bitnami/postgresql
    version: 16.0.1
    values:
      - ./values/postgresql.values.yaml

  # PostgreSQL database monitoring
  - name: prometheus-postgres-exporter
    namespace: db-system
    chart: prometheus-community/prometheus-postgres-exporter
    version: 6.3.1
    values:
      - ./values/postgresql.exporter.values.yaml

  # Factorio
  - name: factorio
    namespace: factorio
    chart: factorio-server-charts/factorio-server-charts
    version: 2.0.1
    values:
      - ./values/factorio.values.yaml.gotmpl

  # Tailscale (VPN)
  - name: tailscale
    namespace: tailscale
    chart: tailscale/tailscale-operator
    version: 1.76.1
    values:
      - ./values/tailscale.values.yaml.gotmpl
