tailscale:
    clientId: ENC[AES256_GCM,data:s5X8PhsHOxmvrjI+CDxaM44=,iv:RCO8TwxXJ7xtczwMSfUce2gCtptCeA/cyfoOIsG9dRs=,tag:bknGZBKcdTC+r6YEgBXWxg==,type:str]
    clientSecret: ENC[AES256_GCM,data:XVWy+FfoNkN0PbrnJe0JHNBqGx6vBrZRh2SFrja4Xrcuph8gO2zlxtBglM78GdoiGXNQfBc+/jNCIo99/P3kVA==,iv:0fgl37r3oHd1gMBzVmJyeweI9Jx3OjwA/GGFwjUe8D8=,tag:8t1G7ehnmBPiWYNfAI9UNQ==,type:str]
factorio:
    game_password: ENC[AES256_GCM,data:0ySQYeG41asmbZo=,iv:Wv5WExtqLoyXr/zV6b0JK2lPIMTgsOWajd26hUsbqVY=,tag:laEOHBOIC7P2Vw+fV67iWg==,type:str]
    rcon_password: ENC[AES256_GCM,data:EV00AQ==,iv:vAxj4IAIWNdIrEr9pqVINO7VlVWZ6vBEozQ17+OJ0Hw=,tag:EuR22GmOB66+W3RgFMKB0Q==,type:str]
db:
    password-root: ENC[AES256_GCM,data:TEdPt+Iru615nkpGsf+Ugqpwpsg=,iv:8/aWiQ8dYd6D/ucEkdxZx2KZoPYfv6KN8f1eJWT0TPs=,tag:btgkbQDfm3QWPvpOXyzC+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-23T21:01:26Z"
    mac: ENC[AES256_GCM,data:UrKIYgW4rfs63D9wR0Kv6DTCKg7HIRd180vMExGLA2gj/UwbIcP5Brd7gwSsXtkNju5uxFAlB1fOLu8mPsaodefYxKzY8H6zTMXplaKjPpkp1VsrPJhmHPWnzm/c+Ob+9Bt5Ain2MceQntAsyLiLsQcCdw4+jMSKoBbuRcPcv30=,iv:Gaz3bghj4PO2gBKa/ADMQ7AUAcg6UeiVB/ZpT/dt+8s=,tag:osUtF4Yco4J7LK8ps8qnKw==,type:str]
    pgp:
        - created_at: "2024-10-23T21:01:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+P21S/K5ckHAQ/9Ha6ruDqc5x2BZbCDNAlU2F6ow4XwqgD+NBC7smOnuX3B
            IcBy5fk6ZsaOV9BLZld6FUlBM9zjiDyhkpyEAKZkXaeYUugr0r8cGJ5fv9SsN7v0
            P4Iudb2HDVyNfHLlTAjE3TWje/hdU/ZxgatSo4s0uDuZ8Vh53IinjQ2B/TZ8VPoU
            aAxqKoq517AiLyVzVbWyZmeTaJBY/q4jxGOjzKKZIrJQWLouaU6sqcV9fhVPF+ru
            GJcT7DK0LURiJPySGGZmu7aEkX5MDGLRwxbK3GsAtSwQcw8PAmBVVfuEab2mmskT
            pQLIA9MI3oCAvzjcgxlIvOkv3mFZGgMAtSKRAiXzmu1vxQSQwSMwnuXT+jpMSamg
            GpcMU/D/cToswcFrv9cWAS64rIbM24JGSjzVCPC+DpIRKwURNWe+MKkTYGIE3UAA
            U967G2OQAmmL+OblGwXnaz8o1CfgtpWY0Lthyj3e+chFeusnSYoiqSzVRuAyyGCl
            ERSlNpS13OwSUCHs910yezVdxLQwZNvrAXeBqmgFRyYeG/XopOAXui9QpxSDiHIL
            vWvHHZj7aqswdWaNTnqRmASVmm1YVTZDZRRbHrgSDnOdu1j1ZwQGLHuXPRWKLkOV
            DOh8fZXYEsORsyh9ottwoDcGqxYFwOgJpgA6uaANInnkIm5dBVJSRNdt9kQPljnS
            XAGoKBzPgcAIHcDvXvcevGdoHPHMbQRMiuUxJWaSB/AZtiJl5Qnl9w27w8EClti/
            8vuZzbnkKaEe3A4uvUavoU+AMHCfIIRM+S1Tu8NloY76VI7ZQOTqeB7PS3Q3
            =AkpM
            -----END PGP MESSAGE-----
          fp: 9570FB9827140BAB9796838C02682CEC265DEFA8
    unencrypted_suffix: _unencrypted
    version: 3.9.1
