tailscale:
    clientId: ENC[AES256_GCM,data:uPFafYEUCgWa1GHoU8xfnu0=,iv:2htmKw59kIAME/GvYn/TcL8VhRKdntK9Apkuq//j5vk=,tag:RCYETpbcppbVGBfh67T+Kg==,type:str]
    clientSecret: ENC[AES256_GCM,data:ElMwGtz6aEaoXP3RPZQUsdgAM9SF9rgdMPiOmxhGD6QdfocwARFjplLhGSVEdCIAvrvwOjaeNOCD5ju98gfkwg==,iv:fvd8U2kOM1dIpLte/zXDeTMcnVji1Od/4vl1/Fd92NI=,tag:6u1kKZw4WU1uX3WTk++9gA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-23T07:57:21Z"
    mac: ENC[AES256_GCM,data:F6QTHwinUndNqoHJMIgOAgPLCow7/y7yA93rU0b0FZMgq35SF4z2/cnXmroDlkGrsvzlu8ANSS6utricaYhFXPJYpzGnd+/4+UTBXIEl54SDkWvod9firTBzjEkj1pTlESTvKLC5hU68ZgotSI/rKG6bgb0BWmm+qw8zDVdZik0=,iv:7ukhAMV0N4WINDhBotA8ErnA8VKDUZvSQpEiLlsuK8c=,tag:S/HurCSkODCKLkUwWSzkdA==,type:str]
    pgp:
        - created_at: "2024-10-23T07:57:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+P21S/K5ckHARAAiXPU7d+jKTl6dTPJRTyqhvin6O2gXkrxpQpTbVjy1UOZ
            j8H4SO5u/gDhS/wX54y/io4BP5k3LH7ElBzEKv2eMGWnQTw1xKJHIIJxfsPg+Toi
            IiVm7gWNdvaXJVWCxruAxp7d6dgbvlLhHVkpJXuTrhMNvWp+Vz/OSTulNSagfdTj
            nK+7dBVp680P3aBFaxZ7FxExb7DC12Qy2o325GOsjgbav4haYqgsuA6K70DCvB9F
            Ch+v5PaX6Dj2ofjPyfE8Ta3gRh1rm00r05aM0lULJRwnIim7McGPIoVCX/z6Ahul
            5RpknmrpLW1W1dUDNwvlrdSqVAdCMNvc56R0XILl2FdYAapwaDoHIPtwdQD/wpQR
            rcjwozE4LzBD/Z9MkrDJ2Z3N05mSKDdyW/TyQVUrq0X/yqatEqiU0s+xXIBfQU4u
            RQztWZcd6loFx//BDmM75e6BSzLOqSVftRBwn4x1WxP7pEtZ8RGlc8gmLdxKwftt
            r6p9ztdJz89aC0seSfxnIogyxn/zr885dfmqmhLOMFgpqD2LJjGSKlTUs5nqk4SM
            nCNji32MzZ2tIVFICP8yxvi39qT1VGagqvwRMR8wswe3lM/qCt7u5jHeS6pNr81K
            giOvv6iXvOfpYYV3PfvtuFjO803v62OLhhBvS2GVs6yrpxuKSvoiU8kW3Gg7YvTS
            XgEPkzLfQjaFGSDRj0EGXFyWaetfAxooyIRf0/trpflAufkKdfkJwc8bvbnU32aG
            QAVUyUoAZio9sDIOQbjQyNCt7Q5KtZlX8Qv69g498HU2qhsBy+HMXx+OmhB/xQU=
            =v7MV
            -----END PGP MESSAGE-----
          fp: 9570FB9827140BAB9796838C02682CEC265DEFA8
    unencrypted_suffix: _unencrypted
    version: 3.9.1
