name: k8s deploy
run-name: k8s deploy
on:
  push:
    paths:
      - "k8s/**"
      - ".github/workflows/deploy-k8s.yaml"

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f k8s
