name: nixos rebuild
run-name: nixos rebuild
on:
  push:
    paths:
      - "nixos/**"
      - ".github/workflows/rebuild-nixos.yaml"

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - uses: appleboy/ssh-action@v1.1.0
        with:
          host: homelab-2
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: echo ${{ secrets.SU_PWD }} | sudo -S nixos-rebuild switch --flake "github:zwolsman/homelab?dir=nixos#$(hostname)"
