name: nixos rebuild
run-name: nixos rebuild
on:
  push:
    paths:
      - "nixos/**"

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - uses: appleboy/ssh-action@v1.1.0
        with:
          host: homelab-0, homelab-1, homelab-2
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: nixos-rebuild test --flake "github:zwolsman/homelab?dir=nixos#$(hostname)"
